arcoiris=("azul","verde","rojo","amarillo")
print(arcoiris)
print("-longuitud arcoiris")
print(len(arcoiris))
animales=("pantera",20,"estatura",1.7,)
print(animales)
print("elementos de la tuplas")
print(animales[2])
rateros = ("juan","ana","pefdro")
y= list(rateros)
y[1]="kiwi"
x=tuple(y)
print(x)
print("agregado elemento")
Nanimal=("body","chetos")
y= list(Nanimal)
print(y)
y.append("tontolin")
otratupla= tuple(y)

print(otratupla)
print("uso de for en tuplas")
for elcolor in arcoiris:
    print(elcolor)